# -*- coding: utf-8 -*-
"""bike_rental_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtBojhCaPDJgNsPiOnCH20Kqsv6nxhxL
"""

import csv

class Bike_Rental:
    def __init__(self):
        self.stock = self.read_stock_from_file()
    
    def read_stock_from_file(self):
        with open("stock.csv", "r") as file:
            reader = csv.reader(file)
            stock = {}
            for row in reader:
                item = row[0]
                quantity = int(row[1])
                stock[item] = quantity
            return stock
        
    def write_stock_to_file(self):
        with open("stock.csv", "w", newline='') as file:
            writer = csv.writer(file)
            for item, quantity in self.stock.items():
                writer.writerow([item, quantity])
       
    
    def rental(self, rental_type, quantity):
        if rental_type not in self.stock:
            print('Invalid rental type')
            return
        
        if quantity > self.stock[rental_type]:
            print('Sorry, we do not have enough bikes')
            return
        
        if rental_type == 'hourly':
            cost = 5 * quantity
        elif rental_type == 'daily':
            cost = 20 * quantity
        elif rental_type == 'weekly':
            cost = 60 * quantity
        
        print('The total rental amount is: $', cost)
    
    def return_bike(self, rental_type, quantity):
        if rental_type not in self.stock:
            print('Invalid rental type')
            return
        
        self.stock[rental_type] += quantity
    
    def display_stock(self):
        print('Current stock:')
        for item, quantity in self.stock.items():
            print(item, ':', quantity)
    
    def family_rental(self, rental_quantity, rental_cost):
        if rental_quantity >= 3:
            cost = rental_cost * 0.7
        else:
            cost = rental_cost
        
        print('The discounted total rental amount is: $', cost)
    
    def receipt(self):
        print("Welcome to Excellent Bike Rental Shop")
        rental_type = input("What type of bikes do you want to rent?\n"
                            "Input '1' for hourly basis\n"
                            "Input '2' for daily basis\n"
                            "Input '3' for weekly basis: ")
        quantity = int(input("Enter the number of bikes you want to rent: "))

        if rental_type == '1':
            rental_type = 'hourly'
        elif rental_type == '2':
            rental_type = 'daily'
        elif rental_type == '3':
            rental_type = 'weekly'
        else:
            print('Invalid rental type')
            return
        
        bike_shop.rental(rental_type, quantity)
        bike_shop.display_stock()
        bike_shop.family_rental(quantity, 5)  

bike_shop = Bike_Rental()
bike_shop.receipt()